import { relationshipCapabilities } from '@/domain/relationships/capabilities';
import type { Capability } from '@/domain/relationships/contracts';
import { RelationshipCapabilityUnavailableError, type RelationshipsRepository } from './relationships';

const unavailable = (capability: Capability): never => { throw new RelationshipCapabilityUnavailableError(capability); };

/** Safe adapter until a typed relationship schema adapter is installed. It never queries or writes. */
export const unavailableRelationshipsRepository: RelationshipsRepository = {
  async capabilities() { return relationshipCapabilities(); },
  async listOrganizations() { return unavailable('organizations'); },
  async getOrganization() { return unavailable('organizations'); },
  async createOrganization() { return unavailable('organizations'); },
  async updateOrganization() { return unavailable('organizations'); },
  async listOrganizationRoles() { return unavailable('organizations'); },
  async replaceOrganizationRoles() { return unavailable('organizations'); },
  async listOrganizationSocialProfiles() { return unavailable('organizations'); },
  async replaceOrganizationSocialProfiles() { return unavailable('organizations'); },
  async listContacts() { return unavailable('contacts'); },
  async getContact() { return unavailable('contacts'); },
  async createContact() { return unavailable('contacts'); },
  async updateContact() { return unavailable('contacts'); },
  async listAffiliations() { return unavailable('contacts'); },
  async createAffiliation() { return unavailable('contacts'); },
  async updateAffiliation() { return unavailable('contacts'); },
  async listStageHistory() { return unavailable('interactions'); },
  async transitionStage() { return unavailable('interactions'); },
  async listInteractions() { return unavailable('interactions'); },
  async createInteraction() { return unavailable('interactions'); },
  async listReferrals() { return unavailable('referrals'); },
  async getReferral() { return unavailable('referrals'); },
  async createReferral() { return unavailable('referrals'); },
  async updateReferral() { return unavailable('referrals'); },
  async verifyReferral() { return unavailable('referrals'); },
  async revokeReferral() { return unavailable('referrals'); },
  async listOpportunities() { return unavailable('opportunities'); },
  async getOpportunity() { return unavailable('opportunities'); },
  async createOpportunity() { return unavailable('opportunities'); },
  async updateOpportunity() { return unavailable('opportunities'); },
  async transitionOpportunityStatus() { return unavailable('opportunities'); },
  async getImportPreview() { return unavailable('imports'); },
  async previewImport() { return unavailable('imports'); },
  async resolveImportConflicts() { return unavailable('imports'); },
  async commitImport() { return unavailable('imports'); },
  async listCampaigns() { return unavailable('campaigns'); },
  async getCampaign() { return unavailable('campaigns'); },
  async createCampaign() { return unavailable('campaigns'); },
  async updateCampaign() { return unavailable('campaigns'); },
  async transitionCampaignStatus() { return unavailable('campaigns'); },
  async evaluateEnrollmentEligibility() { return unavailable('enrollment'); },
  async listEnrollments() { return unavailable('enrollment'); },
  async getEnrollment() { return unavailable('enrollment'); },
  async enroll() { return unavailable('enrollment'); },
  async transitionEnrollmentStatus() { return unavailable('enrollment'); },
  async listEnrollmentEvents() { return unavailable('enrollment'); },
  async listCommunications() { return unavailable('campaigns'); },
  async listReplies() { return unavailable('replies'); },
  async updateReply() { return unavailable('replies'); },
  async listSuppressions() { return unavailable('suppression'); },
  async createSuppression() { return unavailable('suppression'); },
  async updateSuppression() { return unavailable('suppression'); },
  async processUnsubscribe() { return unavailable('unsubscribe'); },
  async listReportMetrics() { return unavailable('reporting'); },
  async search() { return unavailable('search'); },
};
