// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ahqauomkgflopxgnlndd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFocWF1b21rZ2Zsb3B4Z25sbmRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQwMTA2NjcsImV4cCI6MjA3OTU4NjY2N30.WGZoTjcJMSDxG5ss1Oe4T0bSBzhsiijfj-I3DnviWGU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});